# Define our base image
FROM jenkins/jenkins:lts-jdk17

# Define user inside container
USER root

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    g++ \
    curl \
    python3 \
    python3-pip \
    mailutils \
    make \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSL https://deb.nodesource.com/setup_19.x | bash \
    && apt-get install -y nodejs

# Install cypress dependencies
RUN apt-get update && \
    apt-get install -y \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb

# Verify installation
RUN node -v

# Reset to root directory
WORKDIR /

# Erase downloaded archive files
RUN apt-get clean

# Define user inside container
USER jenkins