# Use root/example as user/password credentials
version: '3.1'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_configuration:/var/jenkins_home

  db:
    image: mysql:8.4.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    restart: always
    environment:
      MYSQL_DATABASE: 'coffee'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api:
    build:
      context: .
      dockerfile: Dockerfile-API
    ports:
      - 9000:9000
    depends_on:
      - db

volumes:
  jenkins_configuration: