# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'coffee'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api_coffee:
    image: coffee
    ports:
      - '8181:9000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: coffee
      DB_USER: root
      DB_PASSWORD: root
