name: Coffee Stock CI

on:
  push:
    branches: [ "main", "develope" ]
  pull_request:
    branches: [ "main", "develope" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Gradle
        run: ./gradlew clean test

      - name: Artefacts Upload
        uses: actions/upload-artifact@v3
        with:
          name: Tests report
          path: build/reports/tests/test


  build:

    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Artefacts Upload
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: build/libs/*.jar
